#!/bin/bash
set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "Installing all packages in development mode (repo: $REPO_ROOT)..."
echo "Installing pfa-ir-schema (leaf dependency, must go first)..."
pip install -e "$REPO_ROOT/packages/pfa-ir-schema"
echo "Installing pfa-fx (leaf FX dependency)..."
pip install -e "$REPO_ROOT/packages/pfa-fx"
echo "Installing pfa-ir-verifier..."
pip install -e "$REPO_ROOT/packages/pfa-ir-verifier"
echo "Installing pfa-parser..."
pip install -e "$REPO_ROOT/packages/pfa-parser"
echo "Installing pfa-ir-consolidator..."
pip install -e "$REPO_ROOT/packages/pfa-ir-consolidator"
echo "Installing pfa-analysis..."
pip install -e "$REPO_ROOT/packages/pfa-analysis"
echo "Installing pfa-cli..."
pip install -e "$REPO_ROOT/apps/pfa-cli"
echo ""
echo "All packages installed. Try: pfa --help"
